# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2841e397ab58c4563c7c3eac8ed08b6060de941f5022cf04231d3755ed33fa3f55c53fa8e1fcd3ae686dad24435b44921ebc4033c84c985ce4f0ec319e0fcc0e

test:
  secret_key_base: f7803d5124e4db29199a09a7d35514d355cec9aa4ad65fac41f2447ddb85d084b2fd4298c1b95625f176b267063c7631bc3e38b50299bd11340093a8eca4c644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
